version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: socialNetwork
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - '5433:5432'
    volumes:
      - /c/Users/leosu/postgres/social-network:/var/lib/postgresql/data

